name: Train Forex Models

on:
  push:
    paths:
      - 'train.py'
      - 'requirements.txt'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Run training
        env:
          FASTFOREX_API_KEY: ${{ secrets.FASTFOREX_API_KEY }}
        run: python train.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v3
        with:
          name: forex-models
          path: model/
