name: Train Model

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run training script
        env:
          FASTFOREX_API_KEY: ${{ secrets.FASTFOREX_API_KEY }}
        run: python train.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: forex-model
          path: model/

